jobs:
  - name: runsh-job-pvt
    type: runSh
    allowPublicAccess: false
    steps:
      - IN: sample-scriptpvtgitreporepo
     # - IN: trigger01
    #  - IN: test-trigger01
      - TASK:
        - script: IN/sample-scriptpvtgitreporepo/gitRepo/echo.sh
    flags: job1
    
  - name: runcliscript-job-pvt
    type: runCLI
    allowPublicAccess: true
    steps:      
      - IN: sample-scriptpvtgitreporepo
      - TASK:
        - script: IN/sample-scriptpvtgitreporepo/gitRepo/echo.sh
    flags: job-runcli
        
        
  - name: manifest_dep_pvt
    type: manifest
    steps:
      - IN: sample_img_pvt  
    flags: manifest
  
  - name: deploy_ddc_pvt
    type: deploy
    steps:      
      - IN: manifest_dep_pvt
      - IN: ddc-clusterpvt
    flags: deploy_ddc
    
  - name: runsh-job2-pvt
    type: runSh
    allowPublicAccess: true
    steps:
      - IN: runsh-job-pvt
     # - IN: trigger01
    #  - IN: test-trigger01
      - TASK:
        - script: ls

  - name: runcliscript-job2-pvt
    type: runCLI
    steps:      
      - IN: runcliscript-job-pvt
      - TASK:
        - script: ls
 
    