triggers:
  - name: tr_11
    type: trigger
    version:
      counter: 5
      
  - name: tr_2
    type: trigger
    version:
      counter: 2
      
  - name: tr_3
    type: trigger
    version:
      counter: 0
      
  - name: tr_4
    type: trigger
    version:
      counter: 0
      
  - name: tr_5
    type: trigger
    version:
      counter: 0
      
  - name: tr_6
    type: trigger
    version:
      counter: 0     

  - name: tr_7
    type: trigger
    version:
      counter: 0
      
  - name: tr_8
    type: trigger
    version:
      counter: 0
      